theme: jekyll-theme-minimal
title: "Catherine Mullen, PhD"
description: "PhD Candidate, Department of Foklore and Ethnomusicology, Indiana University"
logo: /assets/img/Mullen_Catherine.jpg
author: "Catherine Mullen, PhD"
