
// this file generated by NC command
const NC_CONFIG = {
  dataset: "H213FA2020Prokopios",
  port: "3000",
  googlea: "0"
};
if (typeof process === "object") module.exports = NC_CONFIG;
if (typeof window === "object") window.NC_CONFIG = NC_CONFIG;